### ISSUE TITLE
App Workflow Testing

### ISSUE THREAD

**Issue by apierr** [devw/script-tag#14]
### Subtasks
- [x] from `Email View `to` Sign-in View`
- [x] from `Email View `to` Register View`
- [x] from ` Sign-in View`to `Forgot Passowrd View`

### Notes

`function changePopup` triggers different templates: 
1. email
2. register
3. sign-in
4. forgot
5. activate (not implemented)
6. pending (spinning)
