### ISSUE TITLE
Adding Script Tag to Store

### ISSUE THREAD

**Issue by apierr** [devw/script-tag#31]
### Subtasks
- [x] implementing shopify-api-node
- [x] defining resovers for getting/deleting/creating scriptTag
- [x] testing the resolvers (**help wanted**)

### Issue
I  perform the query in two ways
1) via https://....myshopify.com/admin/api/2020-07/script_tags.json
2) via shopify-api-node

I get the following results:
- using the same endpoint "`https://....myshopify.com/`" and `different token` I get a different result.
- using the same endpoint "`https://....myshopify.com/`" and the `same token` I get a subset (not the same).

#### References:
1. https://www.npmjs.com/package/shopify-api-node
2. https://github.com/devw/shopify-node-react/issues/4
3. https://paso2020.myshopify.com/admin/api/2020-07/script_tags.json
4. https://paso2020.myshopify.com/admin/api/2020-10/script_tags/count.json

#### From Shopify GraphiQL App

```
query scriptTagsGet {
  scriptTags(first: 4) {
    edges {
      node {
        id
        src
      }
    }
  }
}
```

```
mutation scriptTagDelete($id: ID!) {
  scriptTagDelete(id: $id) {
    deletedScriptTagId
    userErrors {
      field
      message
    }
  }
}

{
  "id": "gid://shopify/ScriptTag/140093554851"
}
```

```
mutation scriptTagCreate($input: ScriptTagInput!) {
  scriptTagCreate(input: $input) {
    scriptTag {
      id
    }
    userErrors {
      field
      message
    }
  }
}

{
  "input": {
    "src": "https://devw.github.io/script-tag/bundle.js"
  }
}

```

#### From `shopify-api-node`

```
const scriptTagsGet = (url) => shopify.scriptTag.list({ src: url });

const scriptTagsDelete = (id) => shopify.scriptTag.delete(id);

const scriptTagCreate = (src) =>
    shopify.scriptTag.create({ event: "onload", src: src });
```
