### ISSUE TITLE
Register Component - Client-side form validation

### ISSUE THREAD

**Issue by apierr** [devw/script-tag#35]
### sub-tasks
- [x] Toggling Submit Button
- [x] All inputs filled 
- [ ] Password is too short (minimum is 5 characters)

### testing query
```
query getLastCutomer {
  customers(first: 1, reverse: true) {
    edges {
      node {
        email
        displayName
        acceptsMarketing
      }
    }
  }
}

```
