### ISSUE TITLE
Translator with YAML

### ISSUE THREAD

**Issue by apierr** [devw/script-tag#37]
### Subtasks
- [x] implementing preprocessor depending on the selected language
- [x] implementing YAML file for three languages (fr, en, it)
- [x] implementing placeholders for email component
- [x] implementing placeholders for sign component
- [x] implementing placeholders for register component

### Implementation

The most efficient solution in terms of network consumption is to use a preprocessor while compiling the js.

```
// webpack.config.js
...
            {
                test: /\.hbs$/i,
                loader: "html-loader",
                options: {
                    preprocessor: (content, _) => {
                        const data = fs.readFileSync(
                            "./src/translation.yaml",
                            "utf8"
                        );
                        return Handlebars.compile(content)(
                            jsyaml.load(data)[config.LANG]
                        );
                    },
                },
            },
...
```

### Yaml example
```
en:
    register:
        title: value1
        subtitle: value2
        first_name_placeholder: 
        last_name_placeholder: 
        password_placeholder: 
        button_text: 
    signin:
        title: value1
        subtitle: value2
        email_placeholder: 
        password_placeholder:

fr:
    register:
        title: value1
        subtitle: value2
        first_name_placeholder: 
        last_name_placeholder: 
        password_placeholder: 
        button_text: 
    signin:
        title: value1
        subtitle: value2
        email_placeholder: 
        password_placeholder:

```

### TODO
- complete the translation for all components
